### ISSUE TITLE
Update website page structure

### ISSUE THREAD

**Issue by nsewnath** [futres/futres_website#15]
- [ ] Get Involved
- Data tutorial

- [ ] About
- About
- How it works
- Team
- News 
- Contact Us

- [ ] Research
- Community Projects
- Official Publications (include google form link)
- Presentations

- [ ] Resources
- Dashboard (rename to Data Dashboard)
- R Shiny app
- R package
- teaching resources (renamed from outreach)
- youtube channel

NOTE: Maybe try to move links from parent header

Keep Workshops the same

**Comment by meghalithic** [comment]
https://futres.shinyapps.io/pyConvApp/

**Comment by meghalithic** [comment]
Get involved should have the contact page

**Comment by meghalithic** [comment]
get rid of "News" page

**Comment by meghalithic** [comment]
community projects is the projects tab; remove projects tab

**Comment by meghalithic** [comment]
under get involved, have term request that links to issues in FOVT

rshiny, rpackage, and youtube all link to direct pages
